### ISSUE TITLE
File manager in panel not working

### ISSUE THREAD

**Issue by skippybossx** [MrFlacko/Scripts#1]
Hi, great job with the script!

However i can't use file manager inside the panel after your script installation,

Gets:
File Error
An error was encountered while processing this request.

**Comment by MrFlacko** [comment]
I don't believe this is an issue with the script
try doing a reinstall of the script following the video and it should work nicely.

I'm currently working on a new script that works a heap nicer. 
https://github.com/MrFlacko/pterodactyl-installer

I will also be doing another video on that.
If you have any further issues you can join the discord to help you out.
https://discord.gg/aeJR3KM

You can also talk to a heap of smart people about it in the Pterodactyl Discord
https://discord.gg/hkXCCVx

**Comment by skippybossx** [comment]
Yah.. i figured out how to solve it.
following https://pterodactyl.io/tutorials/mysql_setup.html
You need to create another user like pterodactyluser and create new database host in the panel with pterodactyluser credentials.
Then it works
